/** 오늘 수업 걷기(목업 01) — 원장으로: 판이 서고 지난 숙제가 검사 줄로 오나 · 출결(낙관) · △→어디까지→나머지 · 항목 더하기·미루기 · 늦귀가·보내기 · 글·마감 · 마감 뒤 읽기만 */
import { launch, offline, VIEWS } from "../_browser.mjs";
const APP = process.env.E2E_APP || "http://127.0.0.1:3300";
let n = 0, bad = 0;
const ok = (what, cond, why = "") => { n++; if (cond) console.log(`   ✅ ${what}`); else { bad++; console.log(`   ❌ ${what}${why ? " — " + why : ""}`); } };
const b = await launch(); const ctx = await b.newContext({ viewport: VIEWS[0].viewport }); await offline(ctx); const p = await ctx.newPage();
await p.goto(APP + "/login"); await p.fill("#id-staff", "zz_principal@e2e.test"); await p.fill("#pw-staff", "e2e-pass");
await Promise.all([p.waitForURL((u) => u.pathname === "/"), p.click("form:has(#id-staff) button[type=submit]")]);
// ── 조회 수(속도-상한 오늘 20) — PostgREST 요청 로그(up.sh 가 log-level info 로 켠다)를 화면 한 번 여는 동안 센다. 층(4단)은 여기서 못 재고 check-fast 가 글자로 본다
import { statSync, readFileSync, existsSync } from "node:fs";
const LOG = process.env.E2E_PGRST_LOG || "/var/tmp/e2e-pgrst.log";
const mark = () => (existsSync(LOG) ? statSync(LOG).size : -1);
const requestsSince = (at) => at < 0 ? -1 : readFileSync(LOG, "utf8").slice(at).split("\n").filter((l) => /"(GET|POST|PATCH|DELETE) \//.test(l)).length;
console.log("■ 오늘 수업");
let at = mark();
await p.goto(APP + "/today"); await p.waitForLoadState("networkidle").catch(() => {});
const firstOpen = requestsSince(at);
ok(`처음 열기(판을 세운다) 조회 ≤ 20 — ${firstOpen}`, firstOpen >= 0 && firstOpen <= 20, firstOpen < 0 ? "로그 없음 " + LOG : "");
at = mark();
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
const steady = requestsSince(at);
ok(`다시 열기(판이 있다) 조회 ≤ 20 — ${steady}`, steady >= 0 && steady <= 20, steady < 0 ? "로그 없음 " + LOG : "");
const row = p.locator(".row").first();
ok("리허설 학생 줄이 선다", (await p.locator(".row").count()) >= 1);
ok("어제 숙제 둘이 검사 줄로 왔다", (await row.locator(".panel .chk").count()) === 2, String(await row.locator(".panel .chk").count()));
ok("「검사 안 본 것 2」", (await p.locator(".pill.warn", { hasText: "검사 안 본 것 2" }).count()) === 1, "알약: " + (await p.locator("main .pill").allTextContents()).join(" | "));
console.log("■ 출결 — 낙관적");
await row.locator(".seg[data-g=att] button", { hasText: "지각" }).click(); await p.waitForTimeout(600);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("지각이 저장돼 있다", (await row.locator(".seg[data-g=att] button", { hasText: "지각" }).getAttribute("aria-pressed")) === "true");
console.log("■ 숙제 검사 △ → 어디까지 → 나머지는 다음 숙제로");
if (!(await row.locator(".panel").count())) await row.locator("button.open").click();
const first = row.locator(".panel .hw").first();
if (!(await first.locator(".chk button[data-v=w]").count())) { console.log("   ⚠️ △ 단추가 없다 — row html:", (await row.innerHTML()).replace(/\s+/g, " ").slice(0, 900)); }
await first.locator(".chk button[data-v=w]").click({ timeout: 5000 }); await p.waitForTimeout(300);
ok("△ 누르면 「어디까지·나머지는」이 열린다", (await first.locator(".partial").count()) === 1);
await first.locator(".seg[data-g=upto] button", { hasText: "절반" }).click(); await p.waitForTimeout(300);
await first.locator(".seg[data-g=rest] button", { hasText: "다음 숙제로" }).click(); await p.waitForTimeout(800);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("△·절반이 남아 있다", (await row.locator(".panel .hw").first().locator(".chk button[data-v=w]").getAttribute("aria-pressed")) === "true" && (await row.locator(".panel .hw").first().locator(".seg[data-g=upto] button", { hasText: "절반" }).getAttribute("aria-pressed")) === "true");
ok("나머지가 오늘 숙제 줄로 섰다(원본을 가리킨다)", (await row.locator(".half", { hasText: "그 밖에 · 집" }).locator(".li", { hasText: "지난 숙제의 나머지" }).count()) === 1);
ok("검사 안 본 것이 1로 줄었다", (await p.locator(".pill.warn", { hasText: "검사 안 본 것 1" }).count()) === 1);
console.log("■ 항목 더하기 · 미루기");
const cls = row.locator(".half", { hasText: "그 밖에 · 학원" });
await cls.locator("input[name=text]").fill("의미덩어리 구두테스트 · PSS 1-4"); await cls.locator("button[type=submit]").click(); await p.waitForTimeout(800);
ok("학원 줄이 하나 섰다", (await row.locator(".half", { hasText: "그 밖에 · 학원" }).locator(".li").count()) === 1);
await row.locator(".half", { hasText: "그 밖에 · 학원" }).locator(".li button", { hasText: "미루기" }).click(); await p.waitForTimeout(800);
ok("미루면 숙제로 간다(지우지 않는다)", (await row.locator(".half", { hasText: "그 밖에 · 학원" }).locator(".li").count()) === 0 && (await row.locator(".half", { hasText: "그 밖에 · 집" }).locator(".li").count()) === 2);
console.log("■ 검사가 끝나면 오늘 학습·숙제가 저절로 깔린다(확정-⑨)");
ok("아직 안 깔렸다(검사 줄 하나 남음) — 교재 머리는 「검사 끝나면 채워집니다」", (await row.locator(".bk .stopnote", { hasText: "검사 끝나면" }).count()) === 1);
await row.locator(".panel .hw").nth(1).locator(".chk button[data-v=d]").click(); await p.waitForTimeout(1200);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
const bk = row.locator(".bk").first();
ok("교재 한 권이 깔렸다(리허설 문법책 · 1회독 · CHAPTER 1)", (await row.locator(".bk").count()) === 1 && (await bk.locator(".bkh .tag", { hasText: "CHAPTER 1" }).count()) === 1);
const bkC = bk.locator(".half").nth(0), bkH = bk.locator(".half").nth(1);
ok("학원 줄 셋(구두테스트·문장훈련·교재 풀기) · 소단원 1-4", (await bkC.locator(".li").count()) === 3 && (await bkC.locator(".li small").first().textContent()).includes("PSS 1-4"));
ok("숙제 줄 둘(문장훈련·워크북 복습) — 오늘 것 복습", (await bkH.locator(".li").count()) === 2 && (await bkH.locator(".seg[data-g=wave-home] button[aria-pressed=true]").textContent()).includes("복습"));
ok("검사 안 본 것 알약이 사라졌다", (await p.locator(".pill.warn", { hasText: "검사 안 본 것" }).count()) === 0);
ok("분량 띠 — 학원 3 (손으로 더한 것은 「그 밖에」로)", (await row.locator(".load .ldn").first().locator("> b").textContent()) === "3");
console.log("■ 회차 — 학습에서 「하나 더」를 누르면 소단원이 둘이 된다(줄은 그대로 셋)");
await bkC.locator(".seg[data-g=wave-class] button", { hasText: "·" }).first().click(); await p.waitForTimeout(1000);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("학습 줄 셋 · 소단원 1-4 · 1-5", (await bk.locator(".half").nth(0).locator(".li").count()) === 3 && (await bk.locator(".half").nth(0).locator(".li small").first().textContent()).includes("1-5"));
ok("학원 항목 수는 줄×소단원 = 6", (await row.locator(".load .ldn").first().locator("> b").textContent()) === "6");
console.log("■ 줄이기 — 필수만 (검사-⑩: 지우지 않고 off)");
await row.locator(".seg[data-g=mode] button", { hasText: "필수만" }).click(); await p.waitForTimeout(1000);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("학습 줄 둘(교재 풀기는 필수가 아님) · 숙제 줄 둘 그대로", (await bk.locator(".half").nth(0).locator(".li").count()) === 2 && (await bk.locator(".half").nth(1).locator(".li").count()) === 2);
await row.locator(".seg[data-g=mode] button", { hasText: "그대로" }).click(); await p.waitForTimeout(1000);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("그대로 → 셋으로 되살아난다", (await bk.locator(".half").nth(0).locator(".li").count()) === 3);
console.log("■ 교재 상태 — 숙제멈춤이면 숙제 반쪽이 「숙제 없음」");
await bk.locator(".stopseg button", { hasText: "숙제멈춤" }).click(); await p.waitForTimeout(1000);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("숙제 반쪽 muted · 숙제 없음", (await bk.locator(".half.muted .stopnote", { hasText: "숙제 없음" }).count()) === 1 && (await row.locator(".load .ldn").nth(1).locator("> b").textContent()) === "2");
await bk.locator(".stopseg button", { hasText: "진행중" }).click(); await p.waitForTimeout(1000);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("진행중 → 숙제 줄 둘이 되살아난다", (await bk.locator(".half").nth(1).locator(".li").count()) === 2);
console.log("■ 교재마다 메모 — 아이 화면에 그대로");
await bk.locator(".half").nth(0).locator(".memoline input[name=text]").fill("어순 뒤집는 문제만 구두로 5개 더"); await bk.locator(".half").nth(0).locator(".memoline input[name=text]").blur(); await p.waitForTimeout(1000);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
ok("학습 메모가 남아 있다", (await bk.locator(".half").nth(0).locator(".memoline input[name=text]").inputValue()) === "어순 뒤집는 문제만 구두로 5개 더");
console.log("■ 늦귀가");
await row.locator("form.lategrid input[name=reason]").fill("워크북 나머지 10-18번");
await row.locator("form.lategrid .seg button", { hasText: "+20분" }).click();
const untilTyped = await row.locator("form.lategrid input[name=untilAt]").inputValue();
ok("+20분이 시각을 채운다", /^\d\d:\d\d$/.test(untilTyped), untilTyped);
await row.locator("form.lategrid button[type=submit]").click(); await p.waitForTimeout(800);
ok("적어 두면 「보내야 함」", (await row.locator(".pill.warn", { hasText: "보내야 함" }).count()) === 1);
await row.locator("button", { hasText: "학부모에게 지금 보내기" }).click(); await p.waitForTimeout(800);
ok("보내기가 오류 없이 큐에 들어간다", (await row.locator("[role=alert]").count()) === 0);
console.log("■ 부모님께 글 · 마감");
await row.locator("textarea[name=comment]").fill("오늘 PSS 1-4 했고 워크북 나머지는 남아서 마쳤습니다.");
await row.locator("button", { hasText: "저장하고 마감" }).click(); await p.waitForTimeout(1000);
await p.reload(); await p.waitForLoadState("networkidle").catch(() => {});
const closedRow = p.locator(".row").first();
ok("마감됨이 뜬다", (await closedRow.locator(".pill", { hasText: "마감됨" }).count()) === 1);
if (!(await closedRow.locator(".panel").count())) await closedRow.locator("button.open").click();
ok("마감 뒤엔 출결이 잠긴다", await closedRow.locator(".seg[data-g=att] button").first().isDisabled());
ok("마감 뒤엔 글을 못 고친다", await closedRow.locator("textarea[name=comment]").isDisabled());
for (const v of VIEWS) { await p.setViewportSize(v.viewport); await p.screenshot({ path: `.tmp/e2e-today-${v.viewport.width}.png`, fullPage: true }); }
await b.close();
console.log(`\n■ 오늘 수업 걷기 ${n}건 · 실패 ${bad}`);
process.exit(bad ? 1 : 0);
