/** 부모님께 글 검사(검사-㊵) — 순수 판단 lib/comment-plan.js: 갈래 다섯·길이 넷 · 상황이 길이를 먼저 고른다 · 그날 상태에서 저절로 · 글자 세기 · 넘으면 문장 끝에서 자른다 · 붙는 줄·미리보기 · AI 초안 그대로인가 · 지시문에 길이 상한 */
import { KIND, CAPS, capName, capOf, pickKind, countChars, isOver, cutAtSentence, sameAsDraft, attached, preview, facts, promptFor } from "../lib/comment-plan.js";
let n = 0, bad = 0;
const ok = (what, cond, why = "") => { n++; if (cond) console.log(`   ✅ ${what}`); else { bad++; console.log(`   ❌ ${what}${why ? " — " + why : ""}`); } };
const caps = { normal: 100, no_homework: 200, before_exam: 100, after_exam: 300, late_night: 50 };
console.log("■ 갈래 · 길이");
ok("갈래 다섯 — 보통·숙제안함·시험전·시험후·늦은밤", KIND.map(([, v]) => v).join(",") === "보통,숙제안함,시험전,시험후,늦은밤");
ok("길이 넷 — 50·100·200·300 · 50 은 「50자 이하」", CAPS.join(",") === "50,100,200,300" && capName(50) === "50자 이하" && capName(100) === "100자");
ok("상황이 길이를 먼저 고른다(규칙 값) · 줄이 없으면 던진다", capOf("after_exam", caps) === 300 && (() => { try { capOf("normal", {}); return false; } catch { return true; } })());
console.log("■ 그날 상태에서 갈래가 저절로");
ok("서울 21시부터 늦은밤 — 검사에 ✕ 가 있어도", pickKind({ hour: 21, lateFrom: 21, checks: [{ status: "missing" }] }) === "late_night");
ok("20시 · 검사에 ✕ → 숙제안함", pickKind({ hour: 20, lateFrom: 21, checks: [{ status: "done" }, { status: "missing" }] }) === "no_homework");
ok("△ 만 있으면 보통", pickKind({ hour: 20, lateFrom: 21, checks: [{ status: "weak" }] }) === "normal");
ok("시험 전후는 자리만(시험 06) — exam 을 주면 그것", pickKind({ hour: 10, lateFrom: 21, exam: "after" }) === "after_exam" && pickKind({ hour: 10, lateFrom: 21, exam: "before", checks: [{ status: "missing" }] }) === "before_exam");
ok("아무것도 없으면 보통", pickKind({}) === "normal");
console.log("■ 글자 세기 · 문장 끝에서 자르기");
ok("공백 포함 · 줄바꿈은 한 칸 · 앞뒤 공백 안 셈", countChars(" 안녕\n\n하세요 ") === 6 && isOver("가".repeat(101), 100) && !isOver("가".repeat(100), 100));
const t = "오늘은 간접의문문을 다뤘습니다. 어순을 스스로 설명해 냈습니다. 워크북 오답 3개는 다음 시간에 다시 봅니다.";
ok("cap 이하면 그대로", cutAtSentence(t, 300) === t);
const c1 = cutAtSentence(t, 40);
ok("40자면 그 안의 마지막 문장 끝에서 — 「…설명해 냈습니다.」", c1 === "오늘은 간접의문문을 다뤘습니다. 어순을 스스로 설명해 냈습니다." && countChars(c1) <= 40, c1);
const c2 = cutAtSentence("문장 끝이 없는 긴 글자들이 계속 이어지는 경우에는 마지막 띄어쓰기에서 자른다", 20);
ok("문장 끝이 없으면 마지막 띄어쓰기에서 · 글자 중간에서 안 자른다", countChars(c2) <= 20 && !c2.endsWith(" ") && "문장 끝이 없는 긴 글자들이 계속 이어지는 경우에는 마지막 띄어쓰기에서 자른다".startsWith(c2) && c2.length < 20, c2);
ok("띄어쓰기도 없으면 cap 에서", cutAtSentence("가".repeat(30), 10) === "가".repeat(10));
console.log("■ AI 초안 그대로인가");
ok("공백만 다르면 같은 것 · 초안이 없으면 거짓", sameAsDraft("오늘  잘했습니다.\n", "오늘 잘했습니다.") && !sameAsDraft("오늘 잘했습니다.", "") && !sameAsDraft("오늘 잘했습니다!", "오늘 잘했습니다."));
console.log("■ 글 밑에 저절로 붙는 줄 · 미리보기");
const next = [{ id: "q1", kind: "word", source: "book", books: { name: "PSS" }, units: { chapter: "CH1", short: "1-4" }, total: 20, cut_pct: 90 }, { id: "q2", kind: "sentence", source: "manual", free_note: "3과", total: null }];
const ls = attached({ next, late: { until_at: "18:40:00", reason: "워크북 나머지" }, warn: { today_disposal: "stay" } });
ok("전체 개수가 있는 시험만 붙는다 — 「다음 시간 단어 시험 — PSS · CH1 › 1-4 20개 · 통과 90%」", ls[0].on && ls[0].text === "다음 시간 단어 시험 — PSS · CH1 › 1-4 20개 · 통과 90%", ls[0].text);
ok("개수를 안 적은 시험은 안 붙고 까닭을 말한다", !ls[1].on && ls[1].text.includes("개수를 안 적어"));
ok("늦귀가 예상 귀가 · 반성문 처분이 붙는다", ls[2].text === "오늘 18:40 귀가 예정 — 워크북 나머지" && ls[3].text.includes("오늘 남아서"));
ok("미리보기 = 글 + 켜진 줄만", preview("오늘 잘했습니다.", ls) === "오늘 잘했습니다.\n다음 시간 단어 시험 — PSS · CH1 › 1-4 20개 · 통과 90%\n오늘 18:40 귀가 예정 — 워크북 나머지\n반성문 — 오늘 남아서 씁니다");
ok("글이 없으면 붙는 줄만", preview("  ", ls).startsWith("다음 시간"));
console.log("■ AI 재료 · 지시문");
const f = facts({ student: { name: "zz", grade: 2 }, sheet: { attend: "late", check: [{ learn_items: { name: "워크북" }, status: "missing" }], class: [{ units: { label: "1-4" }, learn_items: { name: "교재 풀기" } }], home: [], late: { until_at: "18:40:00" } }, quizzes: [{ kind: "word", source: "manual", free_note: "Day 3", pct: 85, passed: false }], keys: "어순 스스로", lines: ls });
ok("사실만 한 줄에 하나 — 출결·검사·학원·시험·늦귀가·키워드·붙는 줄", f.some((x) => x.startsWith("출결: 지각")) && f.some((x) => x.includes("워크북 ✕ 안 해옴")) && f.some((x) => x.includes("교재 풀기 1-4")) && f.some((x) => x.includes("85%") && x.includes("재시험")) && f.some((x) => x.includes("18:40까지")) && f.some((x) => x.includes("어순 스스로")) && f.filter((x) => x.startsWith("글 밑에 앱이 붙이는 줄")).length === 3, f.join(" | "));
const pr = promptFor({ kind: "no_homework", cap: 200, samples: ["[보통] 오늘 잘했어요"], rules: "존댓말", factLines: f });
ok("지시문 — 길이 상한 · 상황 안내 · 본보기 · 원장님 조건 · 지어내지 말 것", pr.user.includes("200자 이내") && pr.user.includes("숙제안함") && pr.system.includes("오늘 잘했어요") && pr.system.includes("존댓말") && pr.system.includes("주어진 사실만"));
console.log(`\n■ 부모님께 글 검사 ${n}건 · 실패 ${bad}`);
process.exit(bad ? 1 : 0);
