/** 학교별 표 판단 검사(검사-59) — lib/grid-plan.js 순수 셈: 본 여섯 · 칸 종류 여섯(확정-56 「앱에서 고르기」) · 칸 읽기 · 값 읽기·글(종류마다 · 비면 없음) · 체크 목록 손 · 줄 이름 · 셈 · 칸으로 이동 · 차례 옮기기 · 보드(선택 칸으로 묶기 · 없음은 숨긴 그룹 · ◀ ▶) · 카드 제목 · 따로 챙길 아이들 · 내 표/전체 표 ·
 *  종류 바꿀 때 값 옮겨 담기(되는 것만 · 안 되는 것은 그대로 · 못 옮긴 값이 남아도 화면이 거짓말을 안 한다) · 체크 목록 항목 빼기(5단계-⑥) */
import { TEMPLATES, COL_TYPES, colsFromTemplate, parseCol, parseCell, cellText, toggleItem, addItem, removeItem, checkText, rowTitle, rowSub, counts, jumpTargets, jumpStep, unitGroups, unitPick, moveIn, boardOf, nextOption, cardTitle, watchSummary, visibleGrids, templateOf, convertCell, convertMany } from "../lib/grid-plan.js";
let n = 0, bad = 0;
const ok = (what, cond, why = "") => { n++; if (cond) console.log(`   ✅ ${what}`); else { bad++; console.log(`   ❌ ${what}${why ? " — " + why : ""}`); } };
const J = (x) => JSON.stringify(x);
const thr = (fn) => { try { fn(); return false; } catch { return true; } };
console.log("■ 본 여섯 · 칸 종류 여섯 · 칸 읽기");
ok("본 여섯(시험범위 · 진도체크 · 학사일정 · 교재 · 특이사항 · 빈 표) · 종류 여섯 · 학교별 교재는 칸 5 + 보드 축 「진행 상황」 · 빈 표는 칸 0 · 진도체크는 줄이 학생", TEMPLATES.length === 6 && COL_TYPES.length === 6 && colsFromTemplate(templateOf("books")).length === 5 && templateOf("books").board === "진행 상황" && colsFromTemplate(templateOf("blank")).length === 0 && templateOf("progress").rows === "student" && colsFromTemplate(templateOf("books"))[3].options.join() === "만들기,인쇄,배부,채점", J(TEMPLATES.map((t) => t.key)));
ok("칸 읽기 — 선택은 선택지(쉼표 · 겹침 하나로) · 고르기는 무엇을(교재) · 이름 없음·종류 없음·선택지 없음은 막는다", J(parseCol({ label: " 진행 ", type: "select", options: "만들기, 인쇄,만들기" })) === J({ label: "진행", type: "select", options: ["만들기", "인쇄"] }) && parseCol({ label: "교재", type: "pick", options: { of: "book" } }).options.of === "book" && thr(() => parseCol({ label: "", type: "text" })) && thr(() => parseCol({ label: "x", type: "no" })) && thr(() => parseCol({ label: "x", type: "select", options: "" })));
console.log("■ 값 읽기 · 글");
const sel = { type: "select", options: ["만들기", "인쇄"] }, chk = { type: "checklist" }, pk = { type: "pick", options: { of: "book" } };
ok("글 · 날짜 · 선택 · 예/아니오 · 체크 목록(글줄 ☑/☐) · 고르기 — 비면 null · 틀린 것은 막는다", parseCell({ type: "text" }, "  hi ") === "hi" && parseCell({ type: "text" }, "") === null && parseCell({ type: "date" }, "2026-10-09") === "2026-10-09" && thr(() => parseCell({ type: "date" }, "10/9")) && parseCell(sel, "인쇄") === "인쇄" && thr(() => parseCell(sel, "배부")) && parseCell({ type: "yn" }, "예") === true && parseCell({ type: "yn" }, false) === false && J(parseCell(chk, "☑ 본책\n☐ 워크북")) === J([{ name: "본책", done: true }, { name: "워크북", done: false }]) && J(parseCell(pk, "b1")) === J({ of: "book", id: "b1" }) && parseCell(pk, { id: "" }) === null);
const refs = { books: [{ id: "b1", name: "중등3800제3" }], exams: [{ id: "e1", name: "2학기 중간", school: "신정중" }], units: [{ id: "u1", chapter: "CH1", short: "1-1" }] };
ok("글로 — 날짜 「10/9」 · 예/아니오 · 체크 「1/2 · ☑ 본책 ☐ 워크북」 · 교재 이름 · 회차 「신정중 2학기 중간」 · 단원 「CH1 › 1-1」 · 목록에 없으면 「(교재 하나 — 목록에 없음)」 · 없음은 빈 글", cellText({ type: "date" }, "2026-10-09") === "10/9" && cellText({ type: "yn" }, true) === "예" && cellText(chk, [{ name: "본책", done: true }, { name: "워크북", done: false }]) === "1/2 · ☑ 본책 ☐ 워크북" && cellText(pk, { of: "book", id: "b1" }, refs) === "중등3800제3" && cellText({ type: "pick", options: { of: "exam" } }, { of: "exam", id: "e1" }, refs) === "신정중 2학기 중간" && cellText({ type: "pick", options: { of: "unit" } }, { of: "unit", id: "u1" }, refs) === "CH1 › 1-1" && cellText(pk, { of: "book", id: "zz" }, refs) === "(교재 하나 — 목록에 없음)" && cellText({ type: "text" }, null) === "");
ok("체크 목록 손 — 켜고 끄기 · 더하기(빈 것은 안 더함) · 「1/2」 · 비면 「—」", toggleItem([{ name: "a", done: false }], 0)[0].done === true && addItem([], "x").length === 1 && addItem([], "  ").length === 0 && checkText([{ done: true }, { done: false }]) === "1/2" && checkText([]) === "—");
console.log("■ 줄 · 셈 · 이동 · 차례");
const g = { id: "g1", label: "학교별 교재", rows: "school", state: "active", created_by: "me", board_col: "c4",
  cols: [{ id: "c1", label: "학년", type: "select", options: ["중1", "중2"], sort: 10, state: "active" }, { id: "c2", label: "교재", type: "pick", options: { of: "book" }, sort: 20, state: "active" }, { id: "c3", label: "배부", type: "yn", sort: 30, state: "active" }, { id: "c4", label: "진행 상황", type: "select", options: ["만들기", "인쇄", "배부", "채점"], sort: 40, state: "active" }, { id: "c5", label: "마감", type: "date", sort: 50, state: "active" }, { id: "c9", label: "내린 칸", type: "text", sort: 5, state: "retired" }],
  rows_: [{ id: "r1", school: "옥련여고", sort: 10, state: "active", cells: { c1: "중1", c2: { of: "book", id: "b1" }, c4: "만들기", c5: "2026-10-09" } }, { id: "r2", school: "신정중", sort: 20, state: "active", cells: { c4: "인쇄" } }, { id: "r3", school: "신정중", sort: 30, state: "active", cells: {} }, { id: "r4", school: "내린 줄", sort: 40, state: "retired", cells: {} }] };
ok("줄 이름 — 학교 · 학생(학교 · 학년) · 자유 · 없으면 (이름 없음)", rowTitle({ school: "신정중" }) === "신정중" && rowTitle({ student: "강민서", student_school: "신정중", grade: 2 }) === "강민서" && rowSub({ student: "강민서", student_school: "신정중", grade: 2 }) === "신정중 · 2학년" && rowTitle({ label: "메모" }) === "메모" && rowTitle({}) === "(이름 없음)");
ok("셈 — 표 1종 · 줄 3(내린 줄 뺌) · 칸 5(내린 칸 뺌) · 내린 표 1 · 칸으로 이동 5(번호 · 이름)", J(counts([g, { ...g, id: "g2", state: "retired" }])) === J({ grids: 1, rows: 3, cols: 5, retired: 1 }) && jumpTargets(g.cols).length === 5 && jumpTargets(g.cols)[0].label === "학년", J(counts([g])));
ok("차례 옮기기 — c2 를 왼쪽으로 → c2,c1,c3,c4,c5 (10씩 다시) · 맨 앞을 왼쪽은 null · 없는 것은 막는다", moveIn(g.cols, "c2", "left").map((x) => x.id).join() === "c2,c1,c3,c4,c5" && moveIn(g.cols, "c2", "left")[0].sort === 10 && moveIn(g.cols, "c1", "left") === null && thr(() => moveIn(g.cols, "zz", "left")));
console.log("■ 보드 — 선택 칸으로 묶기 · 카드 = 줄");
const bd = boardOf(g);
ok("축 = 진행 상황(board_col) · 칸 넷(만들기 1 · 인쇄 1 · 배부 0 · 채점 0) · 값 없음 1은 숨긴 그룹 · 선택 칸 둘(학년 · 진행 상황)", bd.axis.id === "c4" && bd.columns.map((c) => `${c.label} ${c.cards.length}`).join() === "만들기 1,인쇄 1,배부 0,채점 0" && bd.none.length === 1 && bd.selects.length === 2, J(bd.columns.map((c) => [c.label, c.cards.length])));
ok("축을 학년으로 바꾸면 중1 1 · 중2 0 · 없음 2 · 선택 칸이 없으면 축 없음", boardOf(g, "c1").columns.map((c) => c.cards.length).join() === "1,0" && boardOf(g, "c1").none.length === 2 && boardOf({ ...g, cols: g.cols.filter((c) => c.type !== "select") }).axis === null);
ok("◀ ▶ — 만들기 ▶ 인쇄 · 만들기 ◀ null · 채점 ▶ null · 값 없으면 첫 선택지 · 카드 제목은 첫 글·고르기 칸(교재 이름) 없으면 줄 이름", nextOption(bd.axis, "만들기", "right") === "인쇄" && nextOption(bd.axis, "만들기", "left") === null && nextOption(bd.axis, "채점", "right") === null && nextOption(bd.axis, null, "right") === "만들기" && cardTitle(g, g.rows_[0], refs) === "중등3800제3" && cardTitle(g, g.rows_[1], refs) === "신정중");
console.log("■ 따로 챙길 아이들 · 내 표/전체 표");
ok("적어 둔 1(빈 메모는 안 센다) · 전체 3", J((({ noted, total }) => ({ noted, total }))(watchSummary([{ student_id: "a", note: "숙제" }, { student_id: "b", note: "  " }], [{}, {}, {}]))) === J({ noted: 1, total: 3 }));
const gs = [{ id: "1", state: "active", created_by: "me" }, { id: "2", state: "active", created_by: "other" }, { id: "3", state: "retired", created_by: "me" }];
ok("원장 전체 표 2(내린 것 뺌) · 원장 내 표 1 · 강사는 제 것만 1(전체 표는 원장만)", visibleGrids(gs, { me: "me", principal: true, mine: false }).length === 2 && visibleGrids(gs, { me: "me", principal: true, mine: true }).length === 1 && visibleGrids(gs, { me: "me", principal: false, mine: false }).length === 1);
console.log("■ 종류 바꿀 때 값 옮겨 담기 · 항목 빼기(5단계-⑥)");
const T = (t, o) => ({ type: t, options: o });
ok("글 → 선택(선택지에 있으면 옮김 · 없으면 그대로) · 글 → 예/아니오(예 · no) · 글 → 날짜(2026.10.9 → 2026-10-09 · 「10/9」 그대로) · 글 → 체크 목록(줄마다 ☑/☐) · 글 → 고르기는 그대로", convertCell(T("text"), T("select", ["인쇄"]), "인쇄").ok && !convertCell(T("text"), T("select", ["인쇄"]), "배부").ok && convertCell(T("text"), T("select", ["인쇄"]), "배부").value === "배부" && convertCell(T("text"), T("yn"), "예").value === true && convertCell(T("text"), T("yn"), "no").value === false && !convertCell(T("text"), T("yn"), "글쎄").ok && convertCell(T("text"), T("date"), "2026.10.9").value === "2026-10-09" && !convertCell(T("text"), T("date"), "10/9").ok && J(convertCell(T("text"), T("checklist"), "☑ 본책\n워크북").value) === J([{ name: "본책", done: true }, { name: "워크북", done: false }]) && !convertCell(T("text"), T("pick", { of: "book" }), "문법책").ok);
ok("→ 글: 날짜·선택 그대로 · 예/아니오 「예」 · 체크 목록 「☑ a\\n☐ b」(되돌려 담으면 같다) · 고르기는 이름(목록에 있을 때만) · 빈 값은 늘 옮김", convertCell(T("date"), T("text"), "2026-10-09").value === "2026-10-09" && convertCell(T("yn"), T("text"), true).value === "예" && convertCell(T("checklist"), T("text"), [{ name: "a", done: true }, { name: "b", done: false }]).value === "☑ a\n☐ b" && J(convertCell(T("text"), T("checklist"), "☑ a\n☐ b").value) === J([{ name: "a", done: true }, { name: "b", done: false }]) && convertCell(T("pick", { of: "book" }), T("text"), { of: "book", id: "b1" }, { books: [{ id: "b1", name: "문법책" }] }).value === "문법책" && !convertCell(T("pick", { of: "book" }), T("text"), { of: "book", id: "zz" }, { books: [] }).ok && convertCell(T("text"), T("yn"), null).ok);
ok("선택 → 선택(선택지 바뀜: 있으면 옮김 · 없으면 그대로) · 예/아니오 → 선택(「아니오」 선택지) · 고르기 → 고르기(무엇을 고르나 같아야)", convertCell(T("select", ["a"]), T("select", ["a", "b"]), "a").ok && !convertCell(T("select", ["a"]), T("select", ["b"]), "a").ok && convertCell(T("yn"), T("select", ["예", "아니오"]), false).value === "아니오" && convertCell(T("pick", { of: "book" }), T("pick", { of: "book" }), { of: "book", id: "b1" }).ok && !convertCell(T("pick", { of: "book" }), T("pick", { of: "exam" }), { of: "book", id: "b1" }).ok);
const cm = convertMany(T("text"), T("select", ["인쇄"]), [{ row_id: "r1", value: "인쇄", title: "신정중" }, { row_id: "r2", value: "배부", title: "연송고" }, { row_id: "r3", value: null, title: "빈" }]);
ok("여럿 — 옮긴 것만 고친다(1) · 못 옮긴 줄 이름(연송고) · 빈 값은 안 센다", J(cm.updates) === J([{ row_id: "r1", value: "인쇄" }]) && cm.moved === 1 && J(cm.unmoved) === J(["연송고"]), J(cm));
ok("못 옮긴 값이 남아도 화면이 거짓말을 안 한다 — 예/아니오 칸의 글 → 「」 · 날짜 칸의 글 → 「」 · 고르기 칸의 글 → 「」 · 체크 목록 칸의 글 → 「」 · 맞는 값은 그대로", cellText(T("yn"), "예정") === "" && cellText(T("date"), "곧") === "" && cellText(T("pick", { of: "book" }), "문법책") === "" && cellText(T("checklist"), "본책") === "" && cellText(T("yn"), true) === "예" && cellText(T("text"), "글") === "글");
ok("체크 목록 항목 빼기 — 둘째를 빼면 하나 · 없는 번호는 그대로", J(removeItem([{ name: "a", done: false }, { name: "b", done: true }], 1)) === J([{ name: "a", done: false }]) && removeItem([{ name: "a", done: false }], 5).length === 1);
ok("칸으로 이동 ◀ ▶((가)-③) — 지금 칸에서 한 칸씩 · 끝이면 null · 지금 칸을 모르면 첫 칸 · 내린 칸은 건너뜀 · 칸이 없으면 null", (() => { const js = jumpTargets([{ id: "a", label: "A", state: "active", sort: 1 }, { id: "x", label: "X", state: "retired", sort: 2 }, { id: "b", label: "B", state: "active", sort: 3 }]); return js.length === 2 && jumpStep(js, "a", "next")?.id === "b" && jumpStep(js, "b", "next") === null && jumpStep(js, "a", "prev") === null && jumpStep(js, "zz", "next")?.id === "a" && jumpStep([], "a", "next") === null; })());
ok("앱에서 고르기 → 단원 한 번에((가)-⑤) — 교재마다 묶고(단원 없는 교재는 빠짐 · 교재 차례 그대로) · 고른 단원에서 교재가 나온다 · 없는 단원은 null", (() => { const bks = [{ id: "b1", name: "문법책" }, { id: "b2", name: "독해책" }, { id: "b3", name: "빈 책" }], us = [{ id: "u2", book_id: "b2", chapter: "U1", short: "1-1" }, { id: "u1", book_id: "b1", chapter: "CH1", short: "1-1" }]; const g = unitGroups(bks, us); return g.length === 2 && g[0].book.id === "b1" && g[0].units[0].id === "u1" && g[1].book.id === "b2" && J(unitPick(us, "u2")) === J({ id: "u2", book_id: "b2" }) && unitPick(us, "zz") === null && unitGroups([], us).length === 0; })());
console.log(`\ncheck-grid ${bad ? "✗" : "✓"} ${n}건 · 실패 ${bad}`);
process.exit(bad ? 1 : 0);
