/** 교재 · 단원 판단 검사(검사-56) — lib/book-plan.js 순수 셈: 단원 한 줄 손질(쪽 「10-12」·문항·핵심 · 막는 것) · 단원 상태 둘 · 같은 교재 열쇠(판·연도·기호만 없앤다) · 활동 차례(줄 순서에서 저절로) · 목록 줄·알약 · 엑셀 읽기(열 이름 후보 · 교재명 이어받기 · 워크북 · 문항범위 → 개수 · 날짜로 바뀐 것 짚기) · 교재 맞추기(교재ID › 이름 › 다른 이름 › 비슷한 이름 · 후보 둘이면 보류) · 올리면 이렇게 됩니다(새로·바뀜·같음·파일에 없는 기존 줄 · 덮어쓰기 차례 · 지우고 새로 · 건너뛰기 · 묶음은 교재를 따른다) · 엑셀로 ·
 *  시트 갈래(단원/교재 — 첫 줄 열 이름) · 교재 시트(머리줄 · 읽기 · 고칠 줄 · 계획 새로/고침/같음/보류 · 고칠 칸 · ⬇ 열) · 묶음(덮어쓰기가 적을 것 · 글 · 📦 줄 · 되돌린 글)(5단계-④) */
import { bookKey, activityOrder, listRows, counts, mapHeaders, parseUnitRows, rangeMangled, countRange, matchBooks, planUpload, mergeOrder, batchFor, exportRows, pagesText, parseUnitEdit, AREA_NAMES, MODES, UNIT_STATE,
         sheetKind, mapBookHeaders, parseBookRows, planBookUpload, bookPatch, exportBookRows, BOOK_HEADERS, splitUnitWrite, runNote, bookRunNote, runLine, undoText } from "../lib/book-plan.js";
let n = 0, bad = 0;
const ok = (what, cond, why = "") => { n++; if (cond) console.log(`   ✅ ${what}`); else { bad++; console.log(`   ❌ ${what}${why ? " — " + why : ""}`); } };
const J = (x) => JSON.stringify(x);
console.log("■ 열쇠 · 활동 차례 · 목록");
ok("같은 교재 열쇠 — 「2025 개정 리딩튜터 (입문)」 = 「리딩튜터 입문」 · 「리딩튜터 기본」은 다르다 · 「능률 1」 ≠ 「능률 2」 · 빈 것은 빈 글자", bookKey("2025 개정 리딩튜터 (입문)") === bookKey("리딩튜터 입문") && bookKey("리딩튜터 입문") !== bookKey("리딩튜터 기본") && bookKey("능률 1") !== bookKey("능률 2") && bookKey("") === "", bookKey("2025 개정 리딩튜터 (입문)"));
ok("활동 차례 — 줄 차례(sort)에서 처음 나오는 순서: 본책 → 워크북 → 단원평가", activityOrder([{ activity: "워크북", sort: 5 }, { activity: "본책", sort: 1 }, { activity: "단원평가", sort: 9 }, { activity: "본책", sort: 2 }]).join(",") === "본책,워크북,단원평가");
const books = [{ id: "b1", code: "G023", name: "중등3800제3", area: "문법", state: "active", units: 18, students: 5, aliases: ["중등 3800제 3권", "3800제3"] }, { id: "b2", code: null, name: "2026 자이스토리 영어독해 기본", area: null, state: "active", units: 0, students: 0, aliases: [] }, { id: "b3", code: "R011", name: "수능딥독1", area: "독해", state: "stopped", units: 12, students: 0, aliases: [] }];
ok("목록 줄 — 영역으로 거른다 · 단원 없음·영역 없음 표시 · 알약(쓰는 교재 2권 · 단원 없음 1 · 영역 없음 1 · 영역별)", listRows(books, "문법").length === 1 && listRows(books)[1].noUnits && listRows(books)[1].noArea && listRows(books)[0].sub === "G023 · 문법" && J(counts(books)) === J({ total: 2, noUnits: 1, noArea: 1, byArea: Object.fromEntries(AREA_NAMES.map((a) => [a, a === "문법" ? 1 : 0])) }), J(counts(books)));
console.log("■ 엑셀 읽기");
ok("머리줄 — 「교재명·대단원·중 단원·소단원·활동명·시작 페이지·끝p·문항 수·문항범위」 → 우리 이름 · 완전히 같은 것을 먼저(「문항범위」가 「문항」에 안 뺏긴다) · 모르는 열 null", J(mapHeaders(["교재명", "대단원", "중 단원", "소단원", "활동명", "시작 페이지", "끝p", "문항 수", "문항범위", "비고"])) === J(["book", "chapter", "mid", "sub", "activity", "page_start", "page_end", "q_count", "q_range", null]), J(mapHeaders(["교재명", "대단원", "중 단원", "소단원", "활동명", "시작 페이지", "끝p", "문항 수", "문항범위", "비고"])));
const sheet = [
  { 교재명: "중등3800제3", 대단원: "CH 8 관계사", 중단원: "PSS 8-1", 소단원: "관계대명사 who", 활동명: "개념·문제", 시작페이지: "p.96", 끝페이지: "", 문항수: "14", 문항범위: "" },
  { 교재명: "", 대단원: "", 중단원: "PSS 8-2", 소단원: "관계대명사 which", 활동명: "개념·문제", 시작페이지: "97", 끝페이지: "97", 문항수: "", 문항범위: "1-16" },
  { 교재명: "", 대단원: "", 중단원: "Practice", 소단원: "", 활동명: "워크북", 시작페이지: "99", 끝페이지: "101", 문항수: "", 문항범위: "2026-01-25" },
  { 교재명: "", 대단원: "", 중단원: "", 소단원: "", 활동명: "", 시작페이지: "", 끝페이지: "", 문항수: "", 문항범위: "" },
  { 교재명: "쓰작1", 대단원: "UNIT 1", 중단원: "", 소단원: "1-1", 활동명: "", 시작페이지: "", 끝페이지: "", 문항수: "3", 문항범위: "" },
];
const parsed = parseUnitRows(sheet);
ok("줄 읽기 — 교재명·대단원이 비면 위 줄을 잇는다 · 이름 될 값이 없는 줄은 버린다(4줄) · 쪽 「p.96」 → 96 · 문항범위 1-16 → 16문항 · 워크북 활동은 워크북 · 활동명 비면 「본책」 · 날짜로 바뀐 범위는 짚고(3행) 개수는 안 센다", parsed.rows.length === 4 && parsed.rows[1].book === "중등3800제3" && parsed.rows[1].chapter === "CH 8 관계사" && parsed.rows[0].page_start === 96 && parsed.rows[1].q_count === 16 && parsed.rows[2].is_workbook === true && parsed.rows[2].q_count === null && J(parsed.mangled) === J([4]) && parsed.rows[3].activity === "본책" && parsed.rows[3].line === 6, J(parsed.rows.map((r) => [r.line, r.book, r.chapter, r.mid, r.sub, r.activity, r.q_count])));
ok("날짜 꼴 — 2026-01-25 · 1/25/2026 · 45678 은 망가진 것 · 「1-25」는 아니다 · 개수 「01-06」 6 · 「3,5,7」 3 · 「1~25」 25", rangeMangled("2026-01-25") && rangeMangled("1/25/2026") && rangeMangled("45678") && !rangeMangled("1-25") && countRange("01-06") === 6 && countRange("3,5,7") === 3 && countRange("1~25") === 25 && countRange("") === null);
console.log("■ 교재 맞추기 · 올리면 이렇게 됩니다");
const groups = matchBooks(parsed.rows, books);
ok("교재 맞추기 — 「중등3800제3」 이름 그대로 · 「쓰작1」은 없어 보류(후보 없음)", groups.length === 2 && groups[0].book?.id === "b1" && groups[0].how === "이름" && groups[1].book === null && groups[1].candidates.length === 0, J(groups.map((g) => [g.name, g.book?.id ?? null, g.how])));
ok("다른 이름·교재ID·비슷한 이름으로도 맞는다 · 후보가 둘이면 못 고른다(보류 + 후보)", matchBooks([{ book: "3800제3", chapter: "x" }], books)[0].how === "다른 이름" && matchBooks([{ book: "아무거나", code: "r011", chapter: "x" }], books)[0].how === "교재ID" && matchBooks([{ book: "2025 개정 수능딥독1", chapter: "x" }], books)[0].how === "비슷한 이름" && (() => { const g = matchBooks([{ book: "3800제", chapter: "x" }], [...books, { id: "b4", code: null, name: "고교 3800제", state: "active", aliases: ["3800제"] }, { id: "b5", code: null, name: "중등 3800제", state: "active", aliases: ["3800제"] }])[0]; return g.book === null && g.candidates.length === 2; })());
const existing = [{ id: "u1", chapter: "CH 8 관계사", mid: "PSS 8-1", sub: "관계대명사 who", activity: "개념·문제", is_workbook: false, sort: 1, page_start: 96, page_end: null, q_count: 14, q_range: null, gist: null, import_batch: "import" },
                  { id: "u2", chapter: "CH 8 관계사", mid: "PSS 8-2", sub: "관계대명사 which", activity: "개념·문제", is_workbook: false, sort: 2, page_start: 97, page_end: 97, q_count: 15, q_range: null, gist: null, import_batch: "import" },
                  { id: "u3", chapter: "CH 9 가정법", mid: "PSS 9-1", sub: "가정법 과거", activity: "개념·문제", is_workbook: false, sort: 3, page_start: 110, page_end: null, q_count: 12, q_range: null, gist: null, import_batch: "import" }];
const plan = planUpload(groups, { b1: existing }, {});
const p1 = plan.perBook[0];
ok("덮어쓰기(기본) — 새로 1(Practice) · 바뀜 1(8-2: 15 → 16) · 같음 1(8-1) · 파일에 없는 기존 줄 1(9-1) · 묶음은 교재를 따라 import(검사-⑰) · 보류 1줄", p1.mode === "overwrite" && p1.added === 1 && p1.changed === 1 && p1.same === 1 && p1.untouched === 1 && p1.batch === "import" && plan.holds.length === 1 && plan.holds[0].lines === 1 && J(plan.totals) === J({ added: 1, changed: 1, same: 1, untouched: 1, holds: 1, books: 1 }), J([p1.added, p1.changed, p1.same, p1.untouched, p1.batch, plan.totals]));
ok("덮어쓰기 차례 — 기존 차례를 지키고 새 줄은 같은 대단원 뒤(Practice 는 8-2 뒤 · 9-1 은 그대로 끝) · 전체에 10·20·30·40 · 있던 줄은 id 를 지닌다", J(p1.rows.map((r) => [r.mid ?? r.sub, r.sort, r.id])) === J([["PSS 8-1", 10, "u1"], ["PSS 8-2", 20, "u2"], ["Practice", 30, null], ["PSS 9-1", 40, "u3"]]) && p1.rows[1].q_count === 16, J(p1.rows.map((r) => [r.mid, r.sort, r.id, r.q_count])));
ok("새 대단원은 끝에 · 지우고 새로는 파일 줄만 · 건너뛰기는 줄 없음 · 묶음 excel(기존 없음)", mergeOrder(existing, [{ chapter: "CH 10 분사", sub: "10-1", activity: "본책" }]).at(-1).chapter === "CH 10 분사" && planUpload(groups, { b1: existing }, { b1: "replace" }).perBook[0].rows.length === 3 && planUpload(groups, { b1: existing }, { b1: "skip" }).perBook[0].rows.length === 0 && planUpload(groups, { b1: existing }, { b1: "skip" }).totals.books === 0 && batchFor([]) === "excel" && batchFor([{ import_batch: "fixture" }]) === "excel" && MODES.length === 3);
console.log("■ 엑셀로");
const ex = exportRows(existing, { name: "중등3800제3", code: "G023" });
ok("내보낼 줄 — 올리기 양식과 같은 열 · 차례대로 · 워크북 Y/빈칸 · 「p.96」", Object.keys(ex[0]).join() === "교재명,교재ID,대단원,중단원,소단원,활동명,워크북,시작페이지,끝페이지,문항수,문항범위,핵심내용" && ex[0].교재ID === "G023" && ex[0].워크북 === "" && pagesText(existing[0]) === "p.96" && pagesText({ page_start: 99, page_end: 101 }) === "p.99-101", J(ex[0]));
console.log("■ 단원 한 줄 손질(4단계-4)");
ok("쪽 「10-12」 → 10·12 · 「p.10」 → 10·10 · 빈 쪽 null · 문항 「14」 → 14 · 빈 문항 null · 핵심은 다듬어서(빈 것 null)", J(parseUnitEdit({ pages: "10-12", qCount: "14", gist: " 관계대명사 " })) === J({ page_start: 10, page_end: 12, q_count: 14, gist: "관계대명사" }) && J(parseUnitEdit({ pages: "p.10" })) === J({ page_start: 10, page_end: 10, q_count: null, gist: null }) && J(parseUnitEdit({})) === J({ page_start: null, page_end: null, q_count: null, gist: null }), J(parseUnitEdit({ pages: "10-12", qCount: "14", gist: " 관계대명사 " })));
ok("막는 것 — 쪽 「십쪽」 · 끝 쪽이 앞 쪽보다 작음 「12-10」 · 문항 「-1」 · 문항 「1.5」", [() => parseUnitEdit({ pages: "십쪽" }), () => parseUnitEdit({ pages: "12-10" }), () => parseUnitEdit({ qCount: "-1" }), () => parseUnitEdit({ qCount: "1.5" })].every((f) => { try { f(); return false; } catch { return true; } }));
ok("단원 상태 둘 — 쓰는 중 · 숨김(지우지 않는다 · 아이 진도 줄이 붙어 있을 수 있다)", UNIT_STATE.map((s) => s[0]).join() === "active,hidden" && UNIT_STATE.map((s) => s[1]).join() === "쓰는 중,숨김");
console.log("■ 시트 갈래 · 교재 시트(5단계-④)");
ok("시트 갈래 — 교재명+대단원 → 단원 · 교재명+소단원 → 단원 · 교재명+영역·레벨·교재비·단원수 → 교재 · 「단원수」 열만으론 단원 시트가 아니다(모름) · 빈 머리줄 → 모름", sheetKind(["교재명", "대단원", "소단원"]) === "units" && sheetKind(["교재명", "소단원"]) === "units" && sheetKind(["교재명", "영역", "레벨", "교재비", "단원수"]) === "books" && sheetKind(["교재명", "단원수"]) === null && sheetKind([]) === null, `${sheetKind(["교재명", "영역", "레벨", "교재비", "단원수"])} · ${sheetKind(["교재명", "단원수"])}`);
ok("교재 시트 머리줄 — 교재명·교재ID·영역·출판사·출판연도·레벨·교재비·구매링크·단원수·비고 → 우리 이름(비고는 모름)", J(mapBookHeaders(["교재명", "교재ID", "영역", "출판사", "출판연도", "레벨", "교재비", "구매링크", "단원수", "비고"])) === J(["name", "code", "area", "publisher", "pub_year", "level", "price", "buy_url", "units", null]), J(mapBookHeaders(["교재명", "교재ID", "영역", "출판사", "출판연도", "레벨", "교재비", "구매링크", "단원수", "비고"])));
const bsheet = [
  { 교재명: " 중등3800제3 ", 교재ID: "g023", 영역: "문법", 출판사: "", 출판연도: "2024", 레벨: "중3", 교재비: "15,000원", 구매링크: "https://x.kr/a", 단원수: "18" },
  { 교재명: "쓰작1", 교재ID: "", 영역: "영작", 출판사: "", 출판연도: "", 레벨: "", 교재비: "", 구매링크: "", 단원수: "" },
  { 교재명: "리딩튜터 입문", 교재ID: "", 영역: "독서", 출판사: "", 출판연도: "", 레벨: "", 교재비: "", 구매링크: "", 단원수: "" },
  { 교재명: "쓰작1", 교재ID: "", 영역: "", 출판사: "", 출판연도: "", 레벨: "", 교재비: "", 구매링크: "www.x.kr", 단원수: "" },
  { 교재명: "", 교재ID: "", 영역: "문법", 출판사: "", 출판연도: "", 레벨: "", 교재비: "", 구매링크: "", 단원수: "" },
];
const bp = parseBookRows(bsheet);
ok("교재 시트 읽기 — 이름 다듬기 · 교재ID 대문자 · 연도 2024 · 교재비 「15,000원」 → 15000 · 빈 칸은 null(모름) · 교재명 없는 줄은 버림 · 고칠 줄 둘(영역 밖 「독서」 · 같은 교재 두 줄 + 링크 꼴) · 단원수는 안 읽는다", bp.rows.length === 2 && bp.rows[0].name === "중등3800제3" && bp.rows[0].code === "G023" && bp.rows[0].pub_year === 2024 && bp.rows[0].price === 15000 && bp.rows[0].publisher === null && bp.rows[1].area === "영작" && bp.bad.length === 2 && bp.bad[0].why.includes("영역이 아닙니다: 독서") && bp.bad[1].why.includes("같은 교재가 위에 또 있습니다(3행)") && bp.bad[1].why.includes("http") && !("units" in bp.rows[0]), J([bp.rows, bp.bad]));
const bplan = planBookUpload(bp.rows, books);
ok("올리면 이렇게 됩니다(교재) — 「중등3800제3」 교재ID 로 맞아 고침(연도 · 레벨 · 교재비 · 구매링크 — 교재ID·영역은 같아 안 센다) · 「쓰작1」 새로 만듦 · 셈 새로 1 · 고침 1 · 같음 0 · 보류 0", bplan.perRow[0].act === "update" && bplan.perRow[0].how === "교재ID" && bplan.perRow[0].labels.join() === "연도,레벨,교재비,구매링크" && bplan.perRow[1].act === "new" && J(bplan.totals) === J({ new: 1, update: 1, same: 0, hold: 0 }), J(bplan.perRow.map((p) => [p.name, p.act, p.how, p.labels])));
ok("고칠 칸 — 시트 값이 있고 다른 칸만(빈 칸은 지우지 않는다 · 같으면 같음) · 후보가 둘이면 보류", J(bookPatch({ area: "문법", level: null, price: 15000 }, { area: "문법", level: "중3", price: 12000 })) === J({ patch: { price: 15000 }, labels: ["교재비"] }) && planBookUpload([{ name: "3800제", code: null }], [...books, { id: "b4", name: "고교 3800제", state: "active", aliases: ["3800제"] }, { id: "b5", name: "중등 3800제", state: "active", aliases: ["3800제"] }]).perRow[0].act === "hold" && planBookUpload([{ name: "중등3800제3", code: null, area: "문법" }], books).perRow[0].act === "same");
ok("⬇ 교재 시트 — 열 아홉(단원수는 셈 열) · 이름 차례", Object.keys(exportBookRows([{ name: "나", code: "B" }])[0]).join() === BOOK_HEADERS.join() && exportBookRows([{ name: "나" }, { name: "가", units: 3 }])[0].교재명 === "가" && exportBookRows([{ name: "가", units: 3 }])[0].단원수 === 3);
console.log("■ 묶음(0057 · 0142)");
const merged = mergeOrder(existing, parsed.rows.filter((r) => r.book === "중등3800제3"));
const sp = splitUnitWrite(existing, merged);
ok("덮어쓰기가 적을 것 — 새 줄 1(Practice) · 고침 3(8-2 내용 + 8-1·9-1 차례만) · before 는 기존 줄 그대로(되돌리기 자료) · 차례만 2", sp.inserts.length === 1 && sp.inserts[0].mid === "Practice" && sp.updates.length === 3 && sp.sortOnly === 2 && sp.updates.find((u) => u.id === "u2").before.q_count === 15 && sp.updates.find((u) => u.id === "u2").row.q_count === 16, J([sp.inserts.map((r) => r.mid), sp.updates.map((u) => [u.id, u.before.sort, u.row.sort]), sp.sortOnly]));
const tens = existing.map((u, i) => ({ ...u, sort: (i + 1) * 10 }));
ok("그대로인 줄은 안 적는다 — 기존 차례가 10·20·30 이고 파일이 같으면 고침 0 · 새 줄 0", splitUnitWrite(tens, mergeOrder(tens, [])).updates.length === 0 && splitUnitWrite(tens, mergeOrder(tens, [])).inserts.length === 0);
ok("묶음 글 — 「교재 1권 · 새로 2 · 바뀜 1 · 차례만 6」 · 지우고 새로·건너뜀은 있을 때만 · 교재 시트 글", runNote({ books: 1, added: 2, changed: 1, sortOnly: 6 }) === "교재 1권 · 새로 2 · 바뀜 1 · 차례만 6" && runNote({ books: 2, added: 0, changed: 0, replaced: 9, skipped: 1 }) === "교재 2권 · 새로 0 · 바뀜 0 · 지우고 새로 9줄 · 건너뜀 1권" && bookRunNote({ created: 1, updated: 1, same: 0 }) === "교재 시트 — 새로 1권 · 고침 1권 · 같음 0");
const rl = runLine({ id: 12, tbl: "units", sheet: "units.xlsx", note: "교재 1권 · 새로 2 · 바뀜 1", at: "2026-09-07T14:10:00+00:00", who: "원장", undone_at: null, can_undo: true });
ok("📦 묶음 줄 — 「#12 단원 · units.xlsx」 · 서울 시각 「09-07 23:10 · 원장」 · 글 · 살아 있음 · 되돌릴 수 있나는 SQL 값 그대로 · 되돌린 줄은 undone + 시각(자정 넘김) · 글이 없으면 셈으로", rl.title === "#12 단원 · units.xlsx" && rl.when === "09-07 23:10 · 원장" && rl.state === "live" && rl.canUndo === true && runLine({ id: 3, tbl: "books", at: "2026-09-07T14:10:00+00:00", undone_at: "2026-09-07T15:00:00+00:00", can_undo: false }).state === "undone" && runLine({ id: 3, tbl: "books", n_insert: 1, n_update: 2 }).note === "새로 1 · 고침 2" && runLine({ id: 3, tbl: "books", undone_at: "2026-09-07T15:00:00+00:00" }).undoneAt === "09-08 00:00" && runLine({ id: 3, tbl: "books", can_undo: false }).canUndo === false, J(rl));
ok("되돌린 글 — 되살림 = 고침 + 되살린 것 · 지움 · 숨김은 있을 때만", undoText({ run: 12, tbl: "units", restored: 7, revived: 0, removed: 2, hidden: 0 }) === "되돌렸습니다 — #12 단원 · 되살림 7 · 지움 2" && undoText({ run: 13, tbl: "units", restored: 0, revived: 3, removed: 0, hidden: 1 }).includes("되살림 3 · 지움 0 · 숨김 1"));
console.log(`\n■ 교재 검사 ${n}건 · 실패 ${bad}`);
process.exit(bad ? 1 : 0);
