/** 나이스 받아오기 판단 검사(검사-51) — lib/neis-plan.js 순수 셈을 본보기로: 학년도 · 주소 · 답 읽기 · 이름 펴기 · 갈래(전국은 낱말 목록으로) · 여러 날 잇기 · 회차 후보 · 출처 열쇠(같은 줄이 하나) */
import { toDate, schoolYear, scheduleUrl, schoolUrl, makeCode, parseCode, readNeis, whyFailed, gradesOf, examName, commonName, kindOf, toEvent, mergeRuns, examPeriods, nationalRows, planImport, bridged } from "../lib/neis-plan.js";
let n = 0, bad = 0;
const ok = (what, cond, why = "") => { n++; if (cond) console.log(`   ✅ ${what}`); else { bad++; console.log(`   ❌ ${what}${why ? " — " + why : ""}`); } };
const WORDS = ["수능", "대학수학능력시험", "학력평가", "전국연합", "학평", "모의고사"];
console.log("■ 날짜·주소·답 읽기");
ok("20260302 → 2026-03-02 · 이상한 것은 null", toDate("20260302") === "2026-03-02" && toDate("2026") === null);
ok("학년도 — 9월이면 올해 3/1~내년 2/28 · 1월이면 지난 학년도 · 윤년 2/29", JSON.stringify(schoolYear("2026-09-06")) === JSON.stringify({ year: 2026, from: "2026-03-01", to: "2027-02-28" }) && schoolYear("2027-01-10").year === 2026 && schoolYear("2028-01-10").to === "2028-02-29");
ok("코드 한 칸 — 「교육청:학교」 · 풀기", makeCode("B10", "7011569") === "B10:7011569" && JSON.stringify(parseCode("B10:7011569")) === JSON.stringify({ atpt: "B10", schul: "7011569" }) && parseCode("") === null);
const u = scheduleUrl("K", { atpt: "B10", schul: "7011569" }, "2026-03-01", "2027-02-28", 2);
ok("일정 주소 — 코드·기간(YYYYMMDD)·쪽·열쇠", u.includes("ATPT_OFCDC_SC_CODE=B10") && u.includes("SD_SCHUL_CODE=7011569") && u.includes("AA_FROM_YMD=20260301") && u.includes("pIndex=2") && u.includes("KEY=K") && schoolUrl("K", "신정중").includes("SCHUL_NM="));
ok("답 읽기 — 잘 됐을 때 줄·총수 · INFO-200 은 비었을 뿐 · RESULT 만 오면 오류", (() => { const r = readNeis({ SchoolSchedule: [{ head: [{ list_total_count: 2 }, { RESULT: { CODE: "INFO-000", MESSAGE: "정상" } }] }, { row: [{ a: 1 }, { a: 2 }] }] }, "SchoolSchedule"); const e = readNeis({ RESULT: { CODE: "INFO-200", MESSAGE: "없음" } }, "SchoolSchedule"); const x = readNeis({ RESULT: { CODE: "ERROR-290", MESSAGE: "키" } }, "SchoolSchedule"); return r.rows.length === 2 && r.total === 2 && e.empty === true && x.empty === false && whyFailed(x.code).includes("인증키"); })());
console.log("■ 이름 펴기 · 갈래");
ok("내신 이름 — 1회고사(4월) → 1학기 중간고사 · 제2차 지필평가(10월) → 2학기 기말고사 · 3회고사 → 2학기 중간고사 · 「2학기 기말」 → 2학기 기말고사 · 수행평가는 그대로", examName("1회고사", "2026-04-20") === "1학기 중간고사" && examName("제2차 지필평가", "2026-10-14") === "2학기 기말고사" && examName("3회고사", "2026-10-01") === "2학기 중간고사" && examName("2학기 기말고사", "2026-12-01") === "2학기 기말고사" && examName("수행평가", "2026-05-01") === "수행평가");
ok("전국 이름 — 「고1·2 전국연합학력평가 실시」 → 모의고사 · 「대수능」 → 대학수학능력시험", commonName("고1·2 전국연합학력평가 실시") === "모의고사" && commonName("2027학년도 대학수학능력시험") === "대학수학능력시험");
ok("갈래 — 쉬는 날 먼저(대수능시험 휴업일 → off) · 전국(낱말 목록) · 수행평가 → assess · 중간고사 → exam · 체육대회 → event · 낱말 목록이 비면 전국이 없다", kindOf("대수능시험 휴업일", "", WORDS) === "off" && kindOf("전국연합학력평가", "", WORDS) === "national" && kindOf("수행평가", "", WORDS) === "assess" && kindOf("2학기 중간고사", "", WORDS) === "exam" && kindOf("체육대회", "", WORDS) === "event" && kindOf("전국연합학력평가", "", []) === "exam" && kindOf("", "휴업일", WORDS) === "off");
ok("학년 칸 — Y 인 것만", gradesOf({ ONE_GRADE_EVENT_YN: "Y", TW_GRADE_EVENT_YN: "N", THREE_GRADE_EVENT_YN: "Y" }).join() === "1,3");
console.log("■ 줄 → 일 · 잇기 · 회차 후보");
const SCH = { id: "s1", name: "신정중", level: "middle", code: "B10:7011569" }, HS = { id: "s2", name: "옥련여고", level: "high", code: "B10:7011570" };
const R = (d, name, g = {}, extra = {}) => ({ AA_YMD: d, EVENT_NM: name, ...Object.fromEntries(Object.entries(g).map(([k, v]) => [k, v])), ...extra });
const rowsM = [R("20261014", "2학기 중간고사", { TW_GRADE_EVENT_YN: "Y" }), R("20261014", "2학기 중간고사", { THREE_GRADE_EVENT_YN: "Y" }), R("20261015", "2학기 중간고사", { TW_GRADE_EVENT_YN: "Y", THREE_GRADE_EVENT_YN: "Y" }), R("20261016", "2학기 중간고사"), R("20261019", "2학기 중간고사"), R("20261003", "개천절"), R("20260930", "토요휴업일"), R("20261113", "대수능시험 휴업일"), R("20260510", "체육대회"), R("20260601", "수행평가")];
const ev = rowsM.map((r) => toEvent(r, SCH, WORDS)).filter(Boolean);
ok("줄 → 일 — 토요휴업일은 안 받는다 · 개천절 off · 수능 휴업일 off · 체육대회 event · 수행평가 assess · 시험은 exam", ev.length === 9 && ev.filter((e) => e.kind === "exam").length === 5 && ev.some((e) => e.raw === "개천절" && e.kind === "off") && ev.some((e) => e.raw === "대수능시험 휴업일" && e.kind === "off") && ev.some((e) => e.kind === "event") && ev.some((e) => e.kind === "assess"));
ok("주말만 건너뛰어 잇는다 — 금(16) → 월(19) 이어짐 · 평일이 비면 끊김", bridged("2026-10-16", "2026-10-19") && !bridged("2026-10-14", "2026-10-16"));
const runs = mergeRuns(ev);
const exam = runs.find((r) => r.kind === "exam");
ok("같은 날 두 줄(학년마다)은 하나 · 14~16 + 19(월) 이 한 기간 · 학년 2·3 모임", runs.filter((r) => r.kind === "exam").length === 1 && exam.from === "2026-10-14" && exam.to === "2026-10-19" && exam.grades.sort().join() === "2,3");
const per = examPeriods(runs, SCH);
ok("학교 회차 후보 — 기간 한 줄 · 학년이 여럿이면 비움 · 열쇠 학교코드:이름:시작날", per.length === 1 && per[0].grade === null && per[0].term_from === "2026-10-14" && per[0].term_to === "2026-10-19" && per[0].source_key === "school:B10:7011569:2학기 중간고사:2026-10-14" && per[0].source === "neis");
const one = examPeriods(mergeRuns([toEvent(R("20261014", "1회고사", { ONE_GRADE_EVENT_YN: "Y" }), HS, WORDS)]), HS);
ok("학년이 하나뿐이면 학년을 적는다(고1) · 4월 아닌 10월 1회고사는 2학기 중간고사", one[0].grade === 1 && one[0].name === "2학기 중간고사");
const rowsH = [R("20261014", "전국연합학력평가", { ONE_GRADE_EVENT_YN: "Y", TW_GRADE_EVENT_YN: "Y" }), R("20261113", "대학수학능력시험", { THREE_GRADE_EVENT_YN: "Y" })];
const rowsH2 = [R("20261014", "고1·2 전국연합학력평가 실시", { ONE_GRADE_EVENT_YN: "Y", TW_GRADE_EVENT_YN: "Y" })];
const plan = planImport([{ school: SCH, rows: rowsM }, { school: HS, rows: rowsH }, { school: { ...HS, id: "s3", name: "연수여고", code: "B10:1" }, rows: rowsH2 }], WORDS);
ok("전국 — 모의고사는 학년마다 하루씩(고1·고2) · 학교 둘이 같은 학평을 적어도 한 줄(열쇠 같음) · 수능 하루 한 줄(영어일 = 그날) · 학교 것 1 = 모두 4", plan.exams.length === 4 && plan.exams.filter((e) => e.scope === "national").length === 3 && plan.exams.some((e) => e.name === "2026년 10월 고1 모의고사" && e.english_on === "2026-10-14" && e.grade === 1) && plan.exams.some((e) => e.name === "대학수학능력시험" && e.english_on === "2026-11-13") && new Set(plan.exams.map((e) => e.source_key)).size === 4, JSON.stringify(plan.exams.map((e) => [e.name, e.grade, e.source_key])));
ok("건너뛴 셈 — 쉬는 날 2 · 행사 1 · 평가 1", JSON.stringify(plan.skipped) === JSON.stringify({ off: 2, event: 1, assess: 1 }), JSON.stringify(plan.skipped));
ok("전국 줄에 학교가 안 붙는다(확정-㊲)", plan.exams.filter((e) => e.scope === "national").every((e) => e.school_id === null));
console.log(`\n■ 나이스 판단 검사 ${n}건 · 실패 ${bad}`);
process.exit(bad ? 1 : 0);
