/** 학생 판단 검사(검사-60) — lib/student-plan.js 순수 셈: 재원 기간 글 · 학년 글 · 반 글 · KPI 여섯(재료 0이면 —) · 교재 막대(stopOn 한 곳) · 성적 줄(등급은 학교 것 › 컷) · 약한 영역(세 번 연속) · 이 달 출결(하원 시각, 답 ⑩) · 단원평가 알약(통과선) · 지나온 것(새것부터) · 목록 줄(재원·퇴원 · 찾기) · 형제 글 · 고치기 양식 읽기 · 아이디 제안·읽기 · 초기화는 앱이 발급한 계정만(대전제-12) · 학부모 계정 이름 읽기((가)-⑩) */
import { tenureText, gradeText2, classLine, kpis, bookLines, scoreRows, weakText, attendRow, unitChips, historyLines, listRows, siblingText, parseStudent, suggestLoginId, parseLoginId, canReset, parseParentName } from "../lib/student-plan.js";
let n = 0, bad = 0;
const ok = (what, cond, why = "") => { n++; if (cond) console.log(`   ✅ ${what}`); else { bad++; console.log(`   ❌ ${what}${why ? " — " + why : ""}`); } };
const J = (x) => JSON.stringify(x);
const thr = (fn) => { try { fn(); return false; } catch { return true; } };
const T = "2026-10-09";
console.log("■ 머리 — 재원 기간 · 학년 · 반");
ok("「2024.03 ~ 재원 2년 7개월」 · 퇴원 「2024.03 ~ 2026.05 퇴원」 · 들어온 날 없음 · 같은 달이면 0개월", tenureText({ joined_on: "2024-03-02", state: "active" }, T) === "2024.03 ~ 재원 2년 7개월" && tenureText({ joined_on: "2024-03-02", left_on: "2026-05-10", state: "left" }, T) === "2024.03 ~ 2026.05 퇴원" && tenureText({ state: "active" }, T) === "들어온 날 없음" && tenureText({ joined_on: "2026-10-01", state: "active" }, T) === "2026.10 ~ 재원 0개월", tenureText({ joined_on: "2024-03-02", state: "active" }, T));
ok("학년 글 「중2」 「고1」 「초6」 · 없으면 빈 글 · 반 글(별명 › 요일 시각) · 반 없음", gradeText2("middle", 2) === "중2" && gradeText2("high", 1) === "고1" && gradeText2("elem", 6) === "초6" && gradeText2("middle", null) === "" && classLine({ nickname: null, weekdays: [1, 3], start_time: "17:00:00" }) === "월·수 17:00" && classLine(null) === "반 없음");
console.log("■ KPI 여섯");
const k = kpis({ hw_done: 5, hw_total: 6, word_pass: 11, word_total: 12, ut_pass: 7, ut_total: 9, att_present: 8, att_absent: 1, att_total: 9, late21: 3, warn: { count: 3, today_disposal: "stay", due: false } }, { "late.repeat_count": "3", "late.repeat_days": "21" });
ok("숙제 83% · 단어 92% · 단원평가 7/9 · 출석 8/9(결석 1) · 늦귀가 3회(21일 안 · 3회째라 bad) · 경고 3회(반성문 1 · bad)", k.map((x) => x.big).join() === "83%,92%,7/9,8/9,3회,3회" && k[3].small === "출석 · 결석 1" && k[4].bad === true && k[4].small === "늦귀가 · 21일 안" && k[5].small === "경고 · 이달 — 반성문 1" && k[5].bad === true, J(k.map((x) => [x.big, x.small, x.bad])));
ok("재료가 0이면 「—」 · 늦귀가 0회는 bad 아님", kpis({}).map((x) => x.big).join() === "—,—,—,—,0회,0회" && kpis({}).every((x) => !x.bad));
console.log("■ 교재 · 성적 · 출결 · 단원평가 · 지나온 것");
const bl = bookLines([{ id: "a", book_id: "b1", name: "중등3800제3", round: 3, order_basis: "chapter", done: 5, total: 18, cursor: "CH6", stop_mode: "running" }, { id: "b", book_id: "b2", name: "능률보카", round: 1, order_basis: "sub", done: 41, total: 60, stop_mode: "book_off", stop_until: "2026-10-17" }, { id: "c", book_id: "b3", name: "지난 멈춤", round: 1, order_basis: "sub", done: 0, total: 0, stop_mode: "book_off", stop_until: "2026-10-01" }], T);
ok("막대 — 5/18 28% · 「3회독 · 대단원 진행 · 지금 CH6」 · 진행중 / 68% 교재멈춤 / 기한 지난 멈춤은 진행중 · 단원 0이면 0%", bl[0].pct === 28 && bl[0].sub === "3회독 · 대단원 진행 · 지금 CH6" && bl[0].stateName === "진행중" && bl[1].pct === 68 && bl[1].stateName === "교재멈춤" && bl[2].state === "running" && bl[2].pct === 0, J(bl.map((x) => [x.pct, x.sub, x.stateName])));
const qs = [{ q_no: 1, kind: "듣기" }, { q_no: 2, kind: "어법" }, { q_no: 3, kind: "어법" }, { q_no: 4, kind: "서술형" }];
const sc = [{ id: "s1", raw: 88, full_score: 100, grade: 2, confirmed: true, wrongs: [2, 3, 4], exam: { name: "1학기 기말", english_on: "2026-07-01", level: "high", cuts: [90, 84], questions: qs } },
  { id: "s2", raw: 82, full_score: 100, grade: null, confirmed: true, wrongs: [2, 3], exam: { name: "1학기 중간", english_on: "2026-04-28", level: "high", cuts: [90, 84, 77], questions: qs } },
  { id: "s3", raw: 79, full_score: 100, grade: null, confirmed: false, wrongs: [2, 3, 1], exam: { name: "2학기 기말", english_on: "2025-12-10", level: "high", cuts: [90, 84, 77], questions: qs } }];
const sr = scoreRows(sc);
ok("성적 줄 — 「26-1 기말」 88 · 학교 등급 2등급 · 틀린 영역 어법 2 › 서술형 1 / 컷으로 3등급 / 확인 전 표시 / 약한 영역 「세 번 연속 어법에서 가장 많이 틀립니다」", sr[0].title === "26-1 기말" && sr[0].grade === "2등급" && sr[0].sum.map((x) => `${x.kind} ${x.n}`).join() === "어법 2,서술형 1" && sr[1].grade === "3등급" && sr[2].pending === true && weakText(sr).kind === "어법" && weakText(sr).text === "세 번 연속 어법에서 가장 많이 틀립니다" && weakText(sr.slice(0, 2)) === null, J(sr.map((x) => [x.title, x.grade, x.sum])));
const at = attendRow([{ date: "2026-10-01", attend: "present", arrived_at: "2026-10-01T08:02:00+00:00", left_at: "2026-10-01T12:31:00+00:00" }, { date: "2026-10-03", attend: "late" }, { date: "2026-10-05", attend: "absent" }, { date: "2026-10-06", attend: "makeup" }, { date: "2026-10-07", attend: null }]);
ok("이 달 출결 — ✓ ⏰ ✕ ↻ 넷(값 없는 날은 뺌) · 등원 17:02 · 하원 21:31(서울 · 답 ⑩)", at.map((a) => a.icon).join("") === "✓⏰✕↻" && at[0].arrived === "17:02" && at[0].left === "21:31" && at[0].title.includes("하원 21:31"), J(at.map((a) => [a.icon, a.arrived, a.left])));
ok("단원평가 알약 — 21/25 ok · 14/25 bad(통과선 80) · 채점 안 한 것은 뺌", J(unitChips([{ id: 1, topic: "관계사", correct: 21, q_count: 25, state: "scored" }, { id: 2, topic: "부정사", correct: 14, q_count: 25, state: "scored" }, { id: 3, topic: "x", state: "made" }], 80).map((u) => [u.text, u.ok])) === J([["관계사 21/25", true], ["부정사 14/25", false]]));
const hl = historyLines({ books: [{ from_date: "2026-03-01", round: 3, name: "중등3800제3" }, { from_date: "2026-07-01", round: 1, name: "수능딥독2" }], classes: [{ from_date: "2026-09-01", class: { weekdays: [1, 3], start_time: "17:00:00" } }, { from_date: "2024-03-02", to_date: "2026-08-31", class: { weekdays: [2, 4], start_time: "17:00:00" } }], consults: [{ at: "2026-08-21T10:00:00Z", way: "학부모 전화", body: "어법이 약하다" }] }, { joined_on: "2024-03-02", state: "active" });
ok("지나온 것 — 새것부터: 반(2026.09 · 갈립니다) · 상담(2026.08) · 교재(2026.07) · 회독 올림(2026.03 · 2회독 진도도 남음) · 반(2024.03 ~ 8/31) · 등원(2024.03)", hl.map((h) => `${h.ym} ${h.title}`).join() === "2026.09 반,2026.08 상담,2026.07 교재 잇기,2026.03 회독 올림,2024.03 반,2024.03 등원" && hl[0].tag === "이 날부터 회차·수강료가 갈립니다" && hl[3].tag === "2회독 진도도 남음", J(hl.map((h) => `${h.ym} ${h.title}`)));
console.log("■ 목록 · 형제 · 양식 · 아이디 · 초기화");
const list = [{ id: "a", name: "강민서", grade: 2, level: "middle", school: "신정중", state: "active", class: { nickname: null, weekdays: [1, 3], start_time: "17:00:00" }, books: ["중등3800제3"], last_consult: "2026-08-21T10:00:00Z" }, { id: "b", name: "김도윤", state: "left", books: [] }, { id: "c", name: "박서준", state: "active", school: "신정중", books: [] }];
const lr = listRows(list, { q: "", show: "active" });
ok("목록 — 재원 2 · 퇴원 1 · 재원 보기 2줄 · 「중2 · 신정중」 · 「월·수 17:00」 · 마지막 상담 8/21 · 교재 없음 · 찾기 「신정」 2 · 퇴원 보기 1", lr.active === 2 && lr.left === 1 && lr.rows.length === 2 && lr.rows[0].gradeText === "중2" && lr.rows[0].classText === "월·수 17:00" && lr.rows[0].lastConsult === "8/21" && lr.rows[1].booksText === "교재 없음" && listRows(list, { q: "신정", show: "active" }).rows.length === 2 && listRows(list, { show: "left" }).rows.length === 1, J(lr.rows.map((r) => [r.name, r.gradeText, r.classText, r.lastConsult])));
ok("형제 글 「👨‍👩‍👦 강민준(고1)」 · 없으면 빈 글", siblingText([{ name: "강민준", grade: 1, level: "high" }]) === "👨‍👩‍👦 강민준(고1)" && siblingText([]) === "");
ok("양식 읽기 — 전화는 숫자만 · 학년 7 은 막음 · 이름 없음 막음 · 날짜 꼴", J(parseStudent({ name: " 강민서 ", grade: "2", schoolId: "s1", phone: "010-1234-5678", parentPhone: "", memo: "", joinedOn: "2024-03-02" })) === J({ name: "강민서", grade: 2, school_id: "s1", phone: "01012345678", parent_phone: null, memo: null, joined_on: "2024-03-02" }) && thr(() => parseStudent({ name: "x", grade: "7" })) && thr(() => parseStudent({ name: "" })) && thr(() => parseStudent({ name: "x", joinedOn: "2024.03" })));
ok("아이디 제안 — 전화 뒤 4자리 「chloe5678」 · 없으면 오늘 MMDD · 읽기(소문자 · chloe + 숫자 넷 — 숫자 넷만 치면 chloe 를 붙인다 · 형제 -2 는 된다(실 DB chloe8729-2) · 다른 꼴은 막는다) · 이관된 계정은 초기화 못 함(대전제-12)", suggestLoginId({ phone: "01012345678" }, T) === "chloe5678" && suggestLoginId({}, T) === "chloe1009" && parseLoginId(" Chloe0515 ") === "chloe0515" && parseLoginId("0515") === "chloe0515" && parseLoginId("chloe0515-2") === "chloe0515-2" && thr(() => parseLoginId("chloe0515-")) && thr(() => parseLoginId("chloe0515-123")) && thr(() => parseLoginId("한글")) && thr(() => parseLoginId("zznew01")) && canReset({ issued_by_app: true }) === true && canReset({ issued_by_app: false }) === false);
ok("학부모 계정 이름 읽기((가)-⑩ — 발급 때 「OO 학부모」를 14 에서 고친다) — 앞뒤 공백 버리고 사이는 하나 · 빈 것·null 막음 · 20자는 되고 21자는 막는다", parseParentName("  김민서   엄마 ") === "김민서 엄마" && thr(() => parseParentName("  ")) && thr(() => parseParentName(null)) && parseParentName("가".repeat(20)) === "가".repeat(20) && thr(() => parseParentName("가".repeat(21))), parseParentName("  김민서   엄마 "));
console.log(`\ncheck-student ${bad ? "✗" : "✓"} ${n}건 · 실패 ${bad}`);
process.exit(bad ? 1 : 0);
